chat/urls.py
from django.conf.urls import patterns, url

from chat import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^(?P<chat_room_id>\d+)/$', views.chat_room, name='chat_room'),
        url(r'^long_poll/(?P<chat_room_id>\d+)/$', views.longpoll_chat_room, name='longpoll_chat_room'),
)

organizersite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

        url(r'^accounts/', include('createusers.urls')),
        url(r'^user/', include('userprofile.urls')),
        url(r'^user/', include('userorganizer.urls')),
        url(r'^chats/', include('chat.urls')),
        url(r'^friends/', include('friends.urls')),
]

userorganizer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

import logging
logr = logging.getLogger(__name__)

class UserOrganizer(models.Model):
    user = models.ForeignKey(User)
    eventname = models.CharField(max_length=50)
    eventabout = models.CharField(max_length=200, null=True)
    event_date = models.DateField()
    event_time = models.TimeField()

userorganizer/forms.py
from django import forms
from models import UserOrganizer

class UserOrganizerForm(forms.ModelForm):
    eventabout = forms.CharField(required=False)
    event_time = forms.TimeField(widget=forms.TimeInput(format='%H:%M'))
    class Meta:
        model = UserOrganizer
        fields = ('id', 'eventname', 'event_date', 'event_time', 'eventabout')

userprofile/forms.py
from django import forms
from models import UserProfile

class UserProfileForm(forms.ModelForm):
    name = forms.CharField(max_length=50,)
    surname = forms.CharField(max_length=50,)
    avatar = forms.FileField(required=False)
    birth_date = forms.DateField(required=False,)
    deskribe = forms.CharField(required=False, max_length=500,)
    class Meta:
        model = UserProfile
        fields = ('avatar', 'name', 'surname', 'birth_date', 'sex', 'deskribe')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}My Base Template{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% get_static_prefix %}css/mainpage.css" >

    <script src="{% get_static_prefix %}js/jquery-3.1.1.js"></script>
    <script src="{% get_static_prefix %}js/ajax.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
    <script>
    $(document).ready(function() {
        $('#id_birth_date').datepicker({
          dateFormat: 'yy-mm-dd',
          changeMonth: true,
          changeYear: true,
          showButtonPanel: true,
          yearRange: "-80:+0",
        });
    });
    </script>
    <script>
    $(document).ready(function() {
        $('#id_event_date').datepicker({
          dateFormat: 'yy-mm-dd',
          changeMonth: true,
          changeYear: true,
          showButtonPanel: true,
          yearRange: "-0:+20",
        });
    });
    </script>
    <script>
    $(document).ready(function(){
        $('#search_date').datepicker({

            dateFormat: 'yy-mm-dd',
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            yearRange: "-0:+20",

        });
        var currentdate = new Date();
        $("#search_date").val($.datepicker.formatDate('yy-mm-dd', currentdate));
        ajax_for_events();


    });
    </script>
    <script>
    $(document).ready(function() {
          $('#id_event_time').timepicker({
              timeFormat: 'HH:mm',
              interval: 60,
              minTime: '1',
              maxHour: '24',
              defaultTime: '6',
              startTime: '1:00',
              dynamic: false,
              dropdown: true,
              scrollbar: true
          });
    });
    </script>


</head>

<body>
	<div id="page">

    <div id="logo">
      <img src="{% static "images/logo2.png" %}" width="200"/>
    </div>

    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/accounts/loggedin/">Strona główna</a></li>
            <li><a href="/user/event/list">Organizer</a></li>
            <li><a href="/user/profile">Proffile</a></li>
            <li><a href="/chats/">Messages</a></li>
            <li><a href="/friends/">Friends</a></li>
            <li><a href="/accounts/logout/">Log Out</a></li>

        </ul>
        {% endblock %}
    </div>

    <div id="content">

        {% block content %}This is the content area{% endblock %}

    </div>

    <div id="friendsbar">
      {% block friendsbar %}Hi {{request.user.username}}{% endblock %}
    </div>

	</div>

</body>
</html>

templates/basestart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Organizer Site{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% get_static_prefix %}css/loginpage.css" >

    <script src="{% get_static_prefix %}js/jquery-2.0.0.min.js"></script>
    <script src="{% get_static_prefix %}js/ajax.js"></script>

</head>

<body>
	<div id="page">
  <div id="logo">
    <img src="{% static "images/logo2.png" %}" width="200"/>
  </div>
    <div id="loginbar">

        {% block content %}This is the content area{% endblock %}

    </div>

    <div id="adblock">{% block ad %}
    Organizer Społecznościowy łączy w sobie funkcjonalność organizera i zalety portalu społecznościowego</br>
    <img src="{% static "images/baner.png" %}" width="500"/>
{% endblock %}
	</div>

</body>
</html>